### ISSUE TITLE
Add some kind of live reload functionality

### ISSUE THREAD

**Issue by joethe** [UMM-CSci-3601/3601-lab2_client-server#15]
Manually restarting our server every time we want to see a change is annoying.

We should add some kind of thing to watch files in the project directory and automatically restart the
server when changes are detected. This will likely end up being much slower than node.js autoreload 
stuff, but it would still be nice to have.

**Comment by joethe** [comment]
@devshawn Pointed this out: http://sparkjava.com/documentation.html#examples

In that example, they use a workaround to avoid loading static files from the 'built' project, instead loading them from the actual project source. This is fine during development, but I think we might want to investigate other solutions.

**Comment by NicMcPhee** [comment]
I'm going to leave this open because it's still a good idea, but I can't seem to find anything obvious that will do this. Sigh.

**Comment by NicMcPhee** [comment]
It's possible that the [`livereload-gradle-plugin`](https://github.com/kordamp/livereload-gradle-plugin) will do what we want? Someone would have to try it out, though.

**Comment by floogulinc** [comment]
> It's possible that the [`livereload-gradle-plugin`](https://github.com/kordamp/livereload-gradle-plugin) will do what we want? Someone would have to try it out, though.

I think this is specifically for live reloading static content and not recompiling and restarting the server which is what we would want here.

**Comment by NicMcPhee** [comment]
Somewhere along the way (years ago, actually), Gradle added the `-t` or `--continuous` flag that does exactly what we want. If you run `./gradlew -t test`, for example (or `check` or `run` instead of `test` if you wish), then it will constantly rebuild and re-run things whenever the Java files change.

I should add that to the write-up and then close this.
