### ISSUE TITLE
Add RouteOverview Javalin plugin

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601/3601-lab2_client-server#169]
See https://github.com/UMM-CSci-3601/3601-iteration-template/commit/70b3d45449a486b19ed464ca795bdab50ee428bf

**Comment by NicMcPhee** [comment]
This doesn't give us a very interesting or super useful page:

![Screen Shot 2022-01-31 at 20 29 26](https://user-images.githubusercontent.com/302297/151904922-e86a72e3-cae0-445d-a447-1ca657dd68d5.png)

It's definitely better than nothing (it lists all the endpoints in one place), but it's not super informative. I wonder if we should be moving the direction of [the OpenAPI plugin](https://javalin.io/plugins/openapi) instead? It looks like it's more configurable and can be used to generate some fairly useful documentation.
