### ISSUE TITLE
Server responds with 201 Created when GETing a pre-existing user

### ISSUE THREAD

**Issue by helloworld12321** [UMM-CSci-3601/3601-lab2_client-server#171]
At these lines: https://github.com/UMM-CSci-3601/3601-lab2_client-server/blob/d44d7b8f73924cb2a5f2bcdd33815431b441fc2e/server/src/main/java/umm3601/user/UserController.java#L34-L37

I'd recommend `200 OK` instead.

(Do we need to call `ctx.status()` at all? It looks like [probably not](https://javalin.io/documentation#endpoint-handlers), but I haven't actually tested that this method works without the call to `status()`. 🤷🏻‍♂️)

**Comment by NicMcPhee** [comment]
This gets closed by #225
