### ISSUE TITLE
How do we feel about those method names in UserControllerSpec?

### ISSUE THREAD

**Issue by helloworld12321** [UMM-CSci-3601/3601-lab2_client-server#172]
Like this one: https://github.com/UMM-CSci-3601/3601-lab2_client-server/blob/d44d7b8f73924cb2a5f2bcdd33815431b441fc2e/server/src/test/java/umm3601/user/UserControllerSpec.java#L47

The underscores read a bit strangely to my eyes, and they're not consistent with our other spec files. I recognize that it's a bit cumbersome to put an all-caps `GET` into a camel-case method name, but I feel like we could probably make it work.

That being said, I don't think this is a particularly pressing change, and if anyone wants to keep them, I'd be fine with that too! :-)

**Comment by helloworld12321** [comment]
It might be worth changing, though, just because whatever we do, the students are going to copy :)

**Comment by NicMcPhee** [comment]
I do think we should change these, and I'm pretty sure that adding Checkstyle will "force" us to change them unless we tell it to ignore these methods.

The two names that come to mind are `getAllUsers()` and `requestAllUsers()`. Maybe the first is better because it reflects the type of request?

**Comment by helloworld12321** [comment]
That works for me! 🙂

I might even suggest a phrase like `canGetAllUsers()`—that way, we indicate this is a test method that asserts stuff.

**Comment by NicMcPhee** [comment]
This will be closed if we merge in #225.
