### ISSUE TITLE
Create a version of the lab which uses Spark (new branch)

### ISSUE THREAD

**Issue by joethe** [UMM-CSci-3601/3601-lab2_client-server#2]
Create a version of the lab which uses [Spark](http://sparkjava.com) rather than NodeJS.
Test it out, and eventually merge it over the old Node version if it works well.

**Comment by joethe** [comment]
New branch (spark-trial) has been created and set up with a basic version of the lab using Spark.

Still todo:
- Dependencies for client side testing (Karma/Jasmine) need to be sorted out.
- Readme needs to be updated.

**Comment by devshawn** [comment]
- [x] Dependencies for client side testing (Karma/Jasmine) need to be sorted out.
- [x] TravisCI stuff needs to be sorted out
- [ ] Readme needs to be updated.
- [ ] Organize directory structure for testing
- [ ] Update LABTASKS
- [ ] Remove GPA calculator

I've added the testing stuff as well as Travis CI stuff (haven't tested it but it works on my angular-spark demo). I can work on README stuff once we know more about how we want to run the projects and stuff.

**Comment by joethe** [comment]
Sounds reasonable. Much of the work on this lab (deciding how we want to run stuff, setting up testing, etc) will transfer to the write-ups for the later labs easily.

**Comment by joethe** [comment]
I think we can consider this to be done, in a general sense.

The lab needs to be polished a bit more, but that can be tracked through more specific issues now
that this transition is done.
