### ISSUE TITLE
Revise ZenHub discussion in write-up to match changes in ZenHub

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab2_client-server#231]
It looks like ZenHub has changed quite a lot since last year, and the write-up needs to be revised in places as a result.

One place that definitely needs changing is that milestones are now sprints.

It also should be clarified somewhere that ZenHub uses issues for stories.

This may also apply to later labs depending on how much they specifically talk about ZenHub.

**Comment by kklamberty** [comment]
KK and John should talk about potentially changing to GitHub Projects and just  bid adieu to ZenHub with its one chart Nic likes,
