### ISSUE TITLE
Do we want to switch to using the body instead of query params in requests?

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab2_client-server#237]
There is an argument to be made that it's better to put the details of a request in the body (which can be encrypted in an HTTPS request) instead of in query params in the path (which can't be encrypted).

Do we want to switch from using query params in our GET requests to instead using the body? Or illustrate both in some fashion?

One thing to be thoughtful about is that if we start using the body for everything it becomes harder for students to try things out and test stuff using "regular" URLs in their browser. We'd probably need to be more explicit/aggressive about introducing a tool like [Postman](https://www.postman.com/) so they'd have a way of trying things out.

If we do go this route it affects everything from Lab 2 through to [the Iteration Template](https://github.com/UMM-CSci-3601/3601-iteration-template/issues/789).

**Comment by floogulinc** [comment]
See my comment https://github.com/UMM-CSci-3601/3601-iteration-template/issues/789#issuecomment-1066051320
