### ISSUE TITLE
Add Thunder Client to recommended extensions and add documentation on how to use it

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601/3601-lab2_client-server#252]
Thunder Client is a lightweight REST client for VS Code similar to things like Insomnia and Postman. It would be very useful for students testing their APIs. It looks like we can even save a set of requests to the VS Code workspace so students have a set of expected things to test and as examples.

https://www.thunderclient.com/

https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client

**Comment by NicMcPhee** [comment]
I think this would be a great idea – thanks for the suggestion!

**Comment by kklamberty** [comment]
We can at least add this as a recommended extension and put in a little bit about how it works by Tuesday, I think.
