### ISSUE TITLE
Update LABTASKS

### ISSUE THREAD

**Issue by joethe** [UMM-CSci-3601/3601-lab2_client-server#3]
With this new semester, we are no longer going to be collecting student answers in their LABTASKS markdown files. The LABTASKS.md file will now serve only to present the questions to students.

Starting with this lab, we need to decide how we want to have students answer those questions, and begin cleaning up the LABTASKS file(s) to reflect that.

**Comment by joethe** [comment]
Some updates in c76b451f22194a4039b57a375a5280e0b71e0cad

Still needs the GPA calculator to be replaced.
We should consider adding 1-2 more questions about JUnit testing, TravisCI, etc.

**Comment by NicMcPhee** [comment]
I still think we're missing some stuff about the client side tasks here, but it's enough to get started on today.

**Comment by joethe** [comment]
Some basic client side instructions added in e701427a82de8d2eb0ac7939f32e9670456fb540
