### ISSUE TITLE
Update README.md to say more about what students will need to do to get started

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/3601-lab2_client-server#33]
The main thing that seems to be missing is how to handle the gradle window when students checkout this project from github.

**Comment by NicMcPhee** [comment]
I'm not sure I understand what the issue is here. Is this about the weird set of windows when you first import the project where you need to say that you're using `gradlew`, etc.?

**Comment by kklamberty** [comment]
Yes - it's about making sure they know what to do with these windows - what options to select.
