### ISSUE TITLE
Replace GPA Calculator with new, more fun task

### ISSUE THREAD

**Issue by devshawn** [UMM-CSci-3601/3601-lab2_client-server#4]
To be decided...

**Comment by joethe** [comment]
I believe we've discussed having them implement some sort of "todo" list, rather than a GPA calculator. A todo list would be more interesting to play with from the database / api side of things later on.

**Comment by joethe** [comment]
We discussed this at the Instructor / TA meeting on Monday Jan. 23.

It seems like a good idea might be to include some kind of tool for parsing JSON files on the server, and then require students to build a rough API using SparkJava for accessing this data (todo list data).
This would also let them develop some rough client side stuff, text fields and buttons and the like.

The API would simply return new JSON files, which makes grading and testing pretty straightforward.

**Comment by joethe** [comment]
It looks like [GSON](http://mvnrepository.com/artifact/com.google.code.gson/gson) might be a good choice here.

**Comment by joethe** [comment]
This can be considered done, in the general sense.

The lab needs to be polished a bit more, but we can track that with more specific issues going forward.
