### ISSUE TITLE
Restructure the code so that it is more like Labs 3 and 4

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab2_client-server#44]
The file structure for this lab is nothing like the file structure for the next two labs, largely because they use Angular, and we just have a little homebrew JS code in this one.

It would be easier for everyone involved if the structure of this codebase was more like that of the subsequent labs.

**Comment by koran023** [comment]
@kklamberty @pluck011 I was able to get the client files by themselves and have the project still run just fine (with passing tests), but when the `src` directory (which contains the server files) is either renamed to `server` or put inside a parent `server`, Gradle can't find `Server.java`.

I'm not sure if this is better than the lab's current structure. I think it does make the client files a little more distinct from server files but having `src` and `client` directories on the same level could potentially cause some confusion. Thoughts?
