### ISSUE TITLE
Illustrate data insertion (& deletion?)

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab2_client-server#50]
We only provide examples of pulling data out of the "DB", but later on they'll need to be inserting, deleting, and updating things. It wouldn't be that hard to add examples of adding (maybe deleting? updating?) users so they set some other types of HTTP requests.

**Comment by kklamberty** [comment]
@NicMcPhee and I discussed this. We think this lab is not the right place for these examples since they are working with static data rather than a database.
