### ISSUE TITLE
Move definition of 

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab2_client-server#53]
https://github.com/UMM-CSci-3601/3601-lab2_client-server/blob/d1863cac5bc4c6b57a626aad6381db0a1cd9cbbd/src/main/resources/public/javascript/users.js#L23

The definition of `HttpClient()` ends up being copied by most students into their `todos.js` file, which clearly isn't great. We should instead move it to something like a `util.js` file which is loaded before `users.js` and therefore available there and (if they load `todos.js` after it) in their code as well.

We should also clean up our naming there to match the [Google JavaScript style guide](https://google.github.io/styleguide/jsguide.html).

Actually, our use of `HttpClient()` as an "object" is quite broken and should be replaced with a simple `get()` function. We also might want to add a second callback for the case where the HTTP request leads to some sort of error.

**Comment by koran023** [comment]
This is closed with PR #61
