### ISSUE TITLE
Expand GET helper function to support error callback(s)

### ISSUE THREAD

**Issue by koran023** [UMM-CSci-3601/3601-lab2_client-server#62]
Right now, if something goes wrong with an HTTP request made via the `get` function in `util.js`, there is no direct method of handling or even displaying an error.

Per @NicMcPhee 's suggestion on #61, we could use this as an early opportunity to demonstrate the use of callbacks in making requests and handling errors and hopefully get people more comfortable using that pattern earlier rather than later.

**Comment by NicMcPhee** [comment]
@floogulinc – How does #93 interact with this? Does your new JS interface obviate this issue?

**Comment by floogulinc** [comment]
Nope. Errors fail silently and you just see the error in the console.
