### ISSUE TITLE
Look at using Mongo in this lab

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601/3601-lab2_client-server#86]
Right now we are using a "fake" database that is just a couple of JSON files loaded as arrays. The issue with this is that it doesn't reflect how we will be doing stuff like filtering with Mongo, where we do that stuff right in the query. We could potentially use MongoDB in this lab.

There are a few options for how to go about this:
1. We could use regular Mongo like in future labs
2. We could use a Mock MongoDB Java library or Gradle plugin and load the JSON right in at runtime.
    1. This is the direction I think we should explore because it will prevent us from needing to deal with a mongo database in testing as well as seeding and such. We only expect students to do read operations so the data being persistent isn't a concern.

**Comment by NicMcPhee** [comment]
Am I correct in assuming that this isn't happening? That's _totally_ fine, but I just wanted to have a sense of what was likely to be ready by Monday when we'd want to finalize the lab.
