### ISSUE TITLE
Switch README badge to GitHub Actions

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601/3601-lab2_client-server#89]
Should probably also add the stuff to remind students to change it also.

**Comment by floogulinc** [comment]
Perhaps we should remove the README badge entirely, they seem somewhat unnecessary nowadays since the testing is built into GitHub and in future labs we will end up with at least three badges that students will have to update for every lab/iteration.

**Comment by NicMcPhee** [comment]
That's an interesting idea, and GitHub will have the little green checkmarks on every commit, PR, etc. I kinda liked the badges, but maybe that's just inertia.

@kklamberty – thoughts?
