### ISSUE TITLE
Running tests in VS Code fails

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab2_client-server#90]
The tests pass fine in `gradle` but fail in VS Code. The problem is that the test code doesn't find the JSON data files, which that VS Code runs the tests from a different "home" directory than Gradle does. We want to keep the Gradle tests passing since they're what's used in GitHub Actions, so if we want to fix this it's presumably a change in VS Code. In Eclipse and IDEA I know we could set the directory where tests were run from, but I don't know what if anything we can do in VS Code about this. Maybe @floogulinc knows?

At a minimum we want to add something to the write-up telling them not to run the tests in VS Code but to use Gradle.

**Comment by NicMcPhee** [comment]
Actually, I would really like to fix this for (at least) two reasons:

* Having to open the report in a web browser when a test fails in Gradle is a pain and certainly slows things down.
* Being able to (re)run individual tests or test files in VS Code is really nice if you're trying to debug a particular problem.

**Comment by floogulinc** [comment]
The fix here might be to include the json in the resources that get built into the JAR (and thus the classpath) instead of referencing a specific directory. I will look into this soon.

**Comment by NicMcPhee** [comment]
Did we get anywhere on this? With the lab rolling out tomorrow it would be good to try to figure this out. @floogulinc didn't have this problem, which was odd, but that was (I think) on his own gear. Everyone else that's tried this in the lab had this issue.

**Comment by floogulinc** [comment]
I will test it in the lab later today. I need to replicate the issue to figure it out.

**Comment by NicMcPhee** [comment]
After some discussion with @floogulinc and @helloworld12321 we've decided that we probably want to just encourage folks to use the command line tools (e.g., Gradle) instead of the VS Code test running. When the students get into the project none of the VS Code test stuff is really going to work (well), so no point in confusing things here.

I'm going to close this.
