### ISSUE TITLE
Use Jackson to simplify reading JSON "DB" file

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab2_client-server#95]
The `Database` class currently still uses `Gson` to do all the JSON parsing. @floogulinc has suggested that now that we've included the `Jackson` dependency, we can use it to do that parsing in a cleaner way. If we do that I think we can eliminate all references to `Gson` in the project! 👍

**Comment by floogulinc** [comment]
This is mainly relevant if we switch to Javalin, since it uses Jackson for its object to JSON conversion.

**Comment by NicMcPhee** [comment]
Which we have done, so this really ought to be done. Not happening for S21, though, as there's not time.
